version: "3.7"
services:
   dzsqlbuild:
      build:
         context: .
         dockerfile: Dockerfile
      hostname: dzsqlbuild
      user: ${CURRENT_UID}
      volumes:
         - type:   bind
           source: ${TARGET}
           target: /home/ubuntu/target
