services:
   dzsqlbuild:
      build:
         context: .
         dockerfile: Dockerfile
      hostname: dzsqlbuild
      volumes:
         - type:   bind
           source: ${TARGET}
           target: /home/ubuntu/target
         - type:   bind
           source: ${GITTRG:-${TARGET}}
           target: /home/ubuntu/gittrg
